def custom_exception_handler(*args):
    print("exception")